# What is NumPy?

NumPy is a low-level Python library written in C & FORTRAN

Used for high-performance numerical & mathematical computations

Provides a powerful N-dimensional array object

Faster than Python lists because it uses contiguous memory

# Applications of NumPy

Powerful N-dimensional arrays

Sophisticated broadcasting functions

Tools for integrating C/C++ & Fortran code

Useful in Linear Algebra, Fourier Transform, Random Numbers

Backbone of ML / Data Science



# Properties of NumPy Arrays

Homogeneous (same data type)

Stores only numbers (int, float, complex)

Fixed size

Faster computation

# Creating NumPy Arrays

In [1]:
import numpy as np

#1️) Using np.array()
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])

arr1

array([1, 2, 3, 4, 5])

In [2]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
#2️) Using zeros, ones, empty
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.empty((2,2))

array([[2.12199579e-314, 4.67296746e-307],
       [5.77068674e-321, 3.79442416e-321]])

In [6]:
#3️) Identity Matrix
np.identity(5)



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
# 4) Using arange()
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.arange(5,16,2)

array([ 5,  7,  9, 11, 13, 15])

In [10]:
# 5) Using linspace()
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [11]:
# 6) Copy
arr2 = arr1.copy()
arr2

array([1, 2, 3, 4, 5])

In [ ]:
🔹 Lists vs NumPy Arrays

NumPy arrays are faster

Consume less memory

More convenient for math operations

In [ ]:
Time comparison example
import time

x = range(100000)
y = range(100000)

start = time.time()
c = [a+b for a,b in zip(x,y)]
print(time.time()-start)

a = np.arange(100000)
b = np.arange(100000)

start = time.time()
c = a+b
print(time.time()-start)


In [ ]:
🔹 Indexing, Slicing & Iteration
arr[1:4]
arr[:,1]
arr[1,:]

for i in arr:
    print(i)

for i in np.nditer(arr):
    print(i)


In [ ]:

🔹 NumPy Array Operations
arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 / arr2

arr1 > 3
arr1 * 2



In [ ]:
🔹 Reshape & Matrix Ops
arr = np.arange(6).reshape(2,3)
arr2 = np.arange(6).reshape(3,2)

arr.dot(arr2)



In [ ]:
🔹 Statistical Functions
arr.min()
arr.max()
arr.sum()
arr.mean()
arr.std()
np.median(arr)



In [ ]:
🔹 Axis Concept
arr.sum(axis=0)   # column-wise
arr.sum(axis=1)   # row-wise

🔹 Reshaping Arrays
arr.ravel()        # flatten
arr.transpose()

🔹 Stacking Arrays
np.vstack((a,b))
np.hstack((a,b))

🔹 Splitting Arrays
np.hsplit(arr, 3)
np.vsplit(arr, 3)

🔹 Fancy Indexing
arr[[0,2,4]]

🔹 Boolean Indexing
arr[arr > 50]
arr[(arr > 50) & (arr < 75)]

🔹 Plotting using NumPy
import matplotlib.pyplot as plt

x = np.linspace(-40,40,100)
y = x*x + 2*x + 6

plt.plot(x,y)
plt.show()



In [ ]:
🔹 Broadcasting

Allows arithmetic between arrays of different shapes

Smaller array expands automatically

🔹 Random Functions
np.random.random()
np.random.seed(1)
np.random.uniform(3,10)
np.random.rand(3,5)
np.random.randint(1,10)

🔹 Max, Min, Argmax, Argmin
np.max(arr)
np.min(arr)
np.argmax(arr)
np.argmin(arr)

🔹 Masking
arr[arr % 2 == 0] = -1

🔹 np.where()
np.where(arr % 2 == 0, 1, 0)

🔹 Sorting
np.sort(arr)     # doesn’t modify original
arr.sort()       # modifies original

🔹 Percentile
np.percentile(arr,25)
np.percentile(arr,50)
np.percentile(arr,75)
np.percentile(arr,99)

🔹 Logical Operators
(arr > 5) & (arr < 15)
(arr > 5) | (arr < 15)
~(arr > 5)

🔹 Handling NaN
np.nan
arr[arr < 0] = np.nan
np.nanmean(arr)